---
customers:
  name: Customers Sheet
  worksheets:
    addresses:
      name: Customer Addresses
      cols:
        id: Customer ID      # refer to column 'id' in the code, translates to the column with header 'Customer ID' in the worksheet
        name: Customer Name
        address: Address
      rows:
        sam: Sam Brady
        george: George Jones
    orders:
      name: Customer Orders
      cols:
        id: Customer ID
        item: Item
    config:
      name: Config
      cols:
        field: Field
        value: Value
