---
abstract: 'Oauth2 connection to Google APIs (currently Drive and Sheets).'
author:
  - 'Robin Murray <mvsjes@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Spreadsheet::Perl: '0'
  Test::Class::Load: '0'
  Test::MockObject::Extends: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Google-RestApi
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '0'
  Furl: '0'
  Hash::Merge: '0'
  JSON: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Net::OAuth2::Client: '0'
  Net::OAuth2::Profile::WebServer: '0'
  Scalar::Util: '0'
  Storable: '0'
  Sub::Retry: '0'
  Tie::Hash: '0'
  Time::Out: '0'
  Type::Params: '0'
  Types::Standard: '0'
  URI: '0'
  URI::QueryParam: '0'
  YAML::Any: '0'
  aliased: '0'
  autodie: '0'
  autovivification: '0'
  constant: '0'
resources:
  repository: https://github.com/mvsjes2/p5-net-google-restapi.git
version: '0.1'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
