#!/usr/bin/perl

use strict;
use warnings;

# to turn on debugging for a particular test, add:
# init_logger($DEBUG);
# at the top of the test file.

# use Carp::Always;
use FindBin;
use lib "$FindBin::RealBin/../lib";
use lib "$FindBin::RealBin/lib";
use lib "$FindBin::RealBin/unit";

# add the ones you want to test here...
# use Test::Google::RestApi::Utils;
use Test::Google::RestApi::SheetsApi4;

Test::Class->runtests();
