#!/usr/bin/env perl

use strict;
use warnings;

# to turn on debugging for a particular test, add:
# init_logger($DEBUG);
# at the top of the test file.

# use Carp::Always;
use FindBin;
use lib "$FindBin::RealBin/../lib";
use lib "$FindBin::RealBin/lib";
use lib "$FindBin::RealBin/unit";

use Test::Unit::Setup;
# init_logger($TRACE);

# add the ones you want to test here...
#use Test::Google::RestApi::Utils;
#use Test::Google::RestApi;
#use Test::Google::RestApi::SheetsApi4;
#use Test::Google::RestApi::SheetsApi4::Spreadsheet;
use Test::Google::RestApi::SheetsApi4::Worksheet;
#use Test::Google::RestApi::SheetsApi4::Range::Col;
#use Test::Google::RestApi::SheetsApi4::RangeGroup::Tie;

Test::Class->runtests();
