GET:
  "https://sheets.googleapis.com/v4/spreadsheets/fake_spreadsheet_id1/values/'Sheet1'!A:A?majorDimension=COLUMNS":
    response: |
      {
        "range": "Sheet1!A1:A1000",
        "majorDimension": "COLUMNS"
      }
    tweaks:
    - get_value
  "https://sheets.googleapis.com/v4/spreadsheets/fake_spreadsheet_id1/values/'Customer%20Addresses'!A:A?majorDimension=COLUMNS":
    response: |
      {
         "majorDimension" : "COLUMNS",
         "range" : "Customer Addresses!A1:A1000",
         "values" : [
            [
               "",
               "Sam Brady",
               "George Jones"
            ]
         ]
      }
