GET:
  "https://sheets.googleapis.com/v4/spreadsheets/fake_spreadsheet_id1/values:batchGet?majorDimension=COLUMNS&ranges='Sheet1'!A%3AA&ranges='Sheet1'!B%3AB&ranges='Sheet1'!C%3AC":
    response: |
      {
        "spreadsheetId": "fake_spreadsheet_id1",
        "valueRanges": [
          {
            "range": "Sheet1!A1:A1000",
            "majorDimension": "COLUMNS"
          },
          {
            "range": "Sheet1!B1:B1000",
            "majorDimension": "COLUMNS"
          },
          {
            "range": "Sheet1!C1:C1000",
            "majorDimension": "COLUMNS"
          }
        ]
      }
    tweaks:
    - batch_get_values
