GET:
  "https://sheets.googleapis.com/v4/spreadsheets/fake_spreadsheet_id1/values/'Sheet1'!1:1?majorDimension=ROWS":
    response: |
      {
        "range" : "Sheet1!A1:Z1",
        "majorDimension" : "ROWS"
      }
    tweaks:
    - get_value
  "https://sheets.googleapis.com/v4/spreadsheets/fake_spreadsheet_id1/values/'Customer%20Addresses'!1:1?majorDimension=ROWS":
    response: |
      {
         "majorDimension" : "ROWS",
         "range" : "Customer Addresses!A1:Z1",
         "values" : [
            [
               "",
               "Customer ID",
               "Customer Name",
               "Address"
            ]
         ]
      }
