PUT:
  "https://sheets.googleapis.com/v4/spreadsheets/fake_spreadsheet_id1/values/'Sheet1'!D4:E5?valueInputOption=USER_ENTERED":
    content: |
      {
         "majorDimension" : "ROWS",
         "range" : "'Sheet1'!D4:E5",
         "values" : [
            [
               "Halifax"
            ]
         ]
      }
    response: |
      {
         "spreadsheetId" : "fake_spreadsheet_id1",
         "updatedCells" : 1,
         "updatedColumns" : 1,
         "updatedRange" : "Sheet1!D4",
         "updatedRows" : 1
      }
    tweaks:
    - batch_update_values
